--
-- Add reputation system
--
ALTER TABLE identity_group DROP COLUMN overall_score, identity_score, own_opinion, peer_opinion;

CREATE TABLE reputation_identity
(
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	identity_id     BIGINT,
	gxs_id          BINARY(16) NOT NULL UNIQUE,
	opinion         ENUM ('negative', 'neutral', 'positive') DEFAULT 'neutral',
	opinion_updated TIMESTAMP(9) NOT NULL,
	pgp_identifier  BIGINT,
	last_used       TIMESTAMP(9) NOT NULL,
	reputation      ENUM ('locally_negative', 'remotely_negative', 'neutral', 'remotely_positive', 'locally_positive')
);
CREATE INDEX idx_reputation_identity_opinion_updated ON reputation_identity (opinion_updated);

CREATE TABLE reputation_identity_opinions
(
	reputation_identity_id BIGINT NOT NULL,
	identifier             BINARY(16) NOT NULL,
	opinion                ENUM ('negative', 'neutral', 'positive') DEFAULT 'neutral'
);
CREATE INDEX idx_reputation_identity_opinions_id ON reputation_identity_opinions (reputation_identity_id);

CREATE TABLE reputation_update
(
	id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	location_id  BIGINT NOT NULL UNIQUE,
	last_updated TIMESTAMP(9) NOT NULL
);

CREATE TABLE reputation_banned_profile
(
	id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	last_used      TIMESTAMP(9) NOT NULL,
	ppg_identifier BIGINT NOT NULL UNIQUE
);
