--
-- Add Channels
--
CREATE TABLE channel_group
(
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description VARCHAR(4096),
	image       VARBINARY(199000) DEFAULT NULL
);

CREATE TABLE channel_message
(
	id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content VARCHAR(8192),
	title   VARCHAR(1024),
	comment VARCHAR(8192),
	image   VARBINARY(199000) DEFAULT NULL,
	read    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE channel_message_files
(
	channel_message_id BIGINT NOT NULL,
	size               BIGINT NOT NULL,
	hash               BINARY(20) NOT NULL,
	name               VARCHAR(1024),
	path               VARCHAR(2048),
	age                INT NOT NULL
);
CREATE INDEX idx_channel_message_id ON channel_message_files (channel_message_id);

-- Add indexes to speed up support linked tables
CREATE INDEX idx_gxs_client_update_messages_gxs_client_update_id ON gxs_client_update_messages (gxs_client_update_id);
CREATE INDEX idx_gxs_group_private_keys_gxs_group_id ON gxs_group_private_keys (gxs_group_id);
CREATE INDEX idx_gxs_group_public_keys_gxs_group_id ON gxs_group_public_keys (gxs_group_id);
CREATE INDEX idx_gxs_group_signatures_gxs_group_id ON gxs_group_signatures (gxs_group_id);
CREATE INDEX idx_gxs_message_signatures_gxs_message_id ON gxs_message_signatures (gxs_message_id);
CREATE INDEX idx_forum_group_admins_forum_group_id ON forum_group_admins (forum_group_id);
CREATE INDEX idx_forum_group_pinned_posts_forum_group_id ON forum_group_pinned_posts (forum_group_id);
