--
-- Add forums
--
CREATE TABLE forum_groups
(
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description VARCHAR(4096)
);

CREATE TABLE forum_admins
(
	forum_groups_id BIGINT NOT NULL,
	admin           BINARY(16)
);

CREATE TABLE forum_pinned_posts
(
	forum_groups_id BIGINT NOT NULL,
	pinned_post     BINARY(20)
);
