--
-- Add file downloads
--
CREATE TABLE file_download
(
	id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name      VARCHAR(255) NOT NULL,
	hash      BINARY(20) NOT NULL,
	size      BIGINT NOT NULL,
	chunk_map VARBINARY(1000000000)
);