/*
 * Copyright (c) 2025 by David Gerber - https://zapek.com
 *
 * This file is part of Xeres.
 *
 * Xeres is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Xeres is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Xeres.  If not, see <http://www.gnu.org/licenses/>.
 */

--
-- Add distant chat backlog
--
CREATE TABLE distant_chat_backlog
(
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	identity_id     BIGINT NOT NULL,
	created         TIMESTAMP(9) NOT NULL,
	own             BOOLEAN NOT NULL,
	message         VARCHAR(199000)
);
CREATE INDEX idx_identity_created ON distant_chat_backlog (identity_id, created);