--
-- Add forums and messages
--
CREATE TABLE forum_groups
(
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description VARCHAR(4096)
);

CREATE TABLE forum_admins
(
	forum_groups_id BIGINT NOT NULL,
	admin           BINARY(16)
);

CREATE TABLE forum_pinned_posts
(
	forum_groups_id BIGINT NOT NULL,
	pinned_post     BINARY(20)
);

CREATE TABLE gxs_messages
(
	id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	gxs_id              BINARY(16)   NOT NULL,
	message_id          BINARY(20)   NOT NULL,
	thread_id           BINARY(20),
	parent_id           BINARY(20),
	original_message_id BINARY(20),
	author_id           BINARY(16),
	name                VARCHAR(512) NOT NULL,
	published           TIMESTAMP,
	flags               INT          NOT NULL DEFAULT 0,
	status              INT          NOT NULL DEFAULT 0,
	child               TIMESTAMP,
	service_string      VARCHAR(512)
);
CREATE INDEX idx_gxs_id ON gxs_messages (gxs_id);
CREATE INDEX idx_message_id ON gxs_messages (message_id);

CREATE TABLE forum_messages
(
    id	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(199000)
);