/*
 * Copyright (c) 2024 by David Gerber - https://zapek.com
 *
 * This file is part of Xeres.
 *
 * Xeres is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Xeres is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Xeres.  If not, see <http://www.gnu.org/licenses/>.
 */

--
-- Add shares and files
--
CREATE TABLE file
(
	id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_id BIGINT NOT NULL,
	name      VARCHAR(255) NOT NULL,
	type      ENUM ('any', 'audio', 'archive', 'cdimage', 'document', 'picture', 'program', 'video') DEFAULT 'any',
	hash      BINARY(20),
	modified  TIMESTAMP NOT NULL,

	CONSTRAINT fk_file_parent FOREIGN KEY (parent_id) REFERENCES file (id)
);
CREATE INDEX idx_parent_name ON file (parent_id, name);
CREATE INDEX idx_hash ON file (hash);

CREATE TABLE share
(
	id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	file_id    BIGINT NOT NULL,
	name       VARCHAR(64) NOT NULL,
	searchable BOOLEAN NOT NULL DEFAULT false,
	browsable  ENUM ('unknown', 'never', 'marginal', 'full', 'ultimate') DEFAULT 'unknown',

	CONSTRAINT fk_share_file FOREIGN KEY (file_id) REFERENCES file (id)
);