@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle rectangle

package "File Transfer" {
  [FileTransferManager] --> [FileTransferRsService]
}

[FileTransferManager] <-> FileTransferAgent

package "FileTransferAgent" {
	[FileLeecher] <<FileProvider>>
	[FileSeeder] <<FileProvider>>
}

[FileLeecher] <--> [FileSystem]
[FileSeeder] <--> [FileSystem]

[FileSystem]

package "Turtle" {
  [TurtleRsService] <-> Tunnels
}

package "Peers" {
  [Peer #1]
  [Peer #2]
}

database "H2 Database" {
  folder "Metadata" {
    [Files]
  }
}

[FileTransferRsService] <--> [TurtleRsService]
[FileTransferRsService] <--> [Metadata]
[FileTransferRsService] <--> [Peers]
[Tunnels] <-> [Peers]

@enduml