@startuml
Juergen -> Heike : GxsSyncGroupRequestItem
rnote over Heike : onAvailableGroupListRequest()
Juergen <- Heike : GROUP_LIST_RESPONSE //List<GxsSyncGroupItems>//
rnote over Juergen: onAvailableGroupListResponse()
Juergen -> Heike: GROUP_LIST_REQUEST //List<GxsSyncGroupItems>//
rnote over Heike: onGroupListRequest()
Heike -> Juergen: TRANSFER //List<GxsTransferGroupItem>//
rnote over Juergen: onGroupReceived()
rnote over Juergen: onGroupReceived()
rnote over Juergen: onGroupReceived()
rnote over Juergen: ...
rnote over Juergen: onGroupsSaved()
@enduml