/*
 * Copyright (c) 2026 by David Gerber - https://zapek.com
 *
 * This file is part of Xeres.
 *
 * Xeres is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Xeres is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Xeres.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.xeres.app.service.backup;

import io.xeres.app.crypto.pgp.PGP;
import io.xeres.app.crypto.rsa.RSA;
import io.xeres.app.crypto.rsid.RSSerialVersion;
import io.xeres.app.crypto.x509.X509;
import io.xeres.app.database.model.identity.IdentityFakes;
import io.xeres.app.database.model.location.Location;
import io.xeres.app.database.model.location.LocationFakes;
import io.xeres.app.database.model.profile.Profile;
import io.xeres.app.database.model.profile.ProfileFakes;
import io.xeres.app.service.IdentityService;
import io.xeres.app.service.LocationService;
import io.xeres.app.service.ProfileService;
import io.xeres.app.service.SettingsService;
import io.xeres.app.xrs.service.identity.IdentityRsService;
import io.xeres.app.xrs.service.identity.item.IdentityGroupItem;
import io.xeres.common.util.ScrambledString;
import jakarta.xml.bind.JAXBException;
import org.bouncycastle.openpgp.PGPException;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockMultipartFile;

import javax.xml.stream.XMLStreamException;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.security.spec.InvalidKeySpecException;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class BackupServiceTest
{
	@Mock
	private ProfileService profileService;

	@Mock
	private LocationService locationService;

	@Mock
	private IdentityService identityService;

	@Mock
	private IdentityRsService identityRsService;

	@Mock
	private SettingsService settingsService;

	@InjectMocks
	private BackupService backupService;

	private static ScrambledString passphrase;
	private static PGPSecretKey pgpSecretKey;
	private static KeyPair rsaKeys;
	private static Profile profile;
	private static X509Certificate certificate;
	private static Location location;
	private static IdentityGroupItem identity;

	@BeforeAll
	static void setup() throws PGPException, IOException, CertificateException
	{
		passphrase = new ScrambledString("");
		pgpSecretKey = PGP.generateSecretKey("Foo", "Generated by Xeres Tests", passphrase, 512);
		rsaKeys = RSA.generateKeys(512);

		profile = ProfileFakes.createOwnProfileWithKeys(pgpSecretKey);
		certificate = X509.generateCertificate(pgpSecretKey, passphrase, rsaKeys.getPublic(), "CN=", "CN=-", Instant.EPOCH, Instant.EPOCH, RSSerialVersion.V07_0001.serialNumber());
		location = LocationFakes.createLocationWithCertificate("Home", profile, certificate);
		identity = IdentityFakes.createOwnWithKeys("Foo");
	}

	@Test
	void backupAndRestore() throws JAXBException, PGPException, XMLStreamException, CertificateException, IOException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException
	{
		when(profileService.getSecretProfileKey()).thenReturn(pgpSecretKey.getEncoded());
		when(locationService.findOwnLocation()).thenReturn(Optional.of(location));

		when(settingsService.getLocationPrivateKeyData()).thenReturn(rsaKeys.getPrivate().getEncoded());
		when(settingsService.getLocationPublicKeyData()).thenReturn(rsaKeys.getPublic().getEncoded());
		when(settingsService.getLocationCertificate()).thenReturn(certificate.getEncoded());
		when(settingsService.getLocalPort()).thenReturn(6232);

		when(identityService.getOwnIdentity()).thenReturn(identity);

		when(profileService.getAllDiscoverableProfiles()).thenReturn(List.of(profile));

		var result = backupService.backup();
		assertNotNull(result);

		backupService.restore(new MockMultipartFile("backup.xml", result), null, passphrase);

		verify(profileService).createOwnProfile(anyString(), any(PGPSecretKey.class), any(PGPPublicKey.class));
		verify(locationService).createOwnLocation(eq("Home"), any(KeyPair.class), any(byte[].class));
		verify(identityRsService).createOwnIdentity(eq("Foo"), any(KeyPair.class), any());
	}

	@Test
	void backupAndRestoreWithNewLocation() throws JAXBException, PGPException, XMLStreamException, CertificateException, IOException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException
	{
		when(profileService.getSecretProfileKey()).thenReturn(pgpSecretKey.getEncoded());
		when(locationService.findOwnLocation()).thenReturn(Optional.of(location));

		when(settingsService.getLocationPrivateKeyData()).thenReturn(rsaKeys.getPrivate().getEncoded());
		when(settingsService.getLocationPublicKeyData()).thenReturn(rsaKeys.getPublic().getEncoded());
		when(settingsService.getLocationCertificate()).thenReturn(certificate.getEncoded());
		when(settingsService.getLocalPort()).thenReturn(6232);

		when(identityService.getOwnIdentity()).thenReturn(identity);

		when(profileService.getAllDiscoverableProfiles()).thenReturn(List.of(profile));

		var result = backupService.backup();
		assertNotNull(result);

		backupService.restore(new MockMultipartFile("backup.xml", result), "newLocation", passphrase);

		verify(profileService).createOwnProfile(anyString(), any(PGPSecretKey.class), any(PGPPublicKey.class));
		verify(locationService).generateOwnLocation(eq("newLocation"), any(ScrambledString.class));
		verify(identityRsService).generateOwnIdentity(anyString(), eq(true), any(ScrambledString.class));
	}
}