/*
 * Copyright (c) 2026 by David Gerber - https://zapek.com
 *
 * This file is part of Xeres.
 *
 * Xeres is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Xeres is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Xeres.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.xeres.app.service.backup;

import io.xeres.app.crypto.pgp.PGP;
import io.xeres.app.crypto.rsa.RSA;
import io.xeres.app.crypto.rsid.RSId;
import io.xeres.app.crypto.rsid.RSIdFakes;
import io.xeres.app.crypto.rsid.RSSerialVersion;
import io.xeres.app.crypto.x509.X509;
import io.xeres.app.database.model.identity.IdentityFakes;
import io.xeres.app.database.model.location.Location;
import io.xeres.app.database.model.location.LocationFakes;
import io.xeres.app.database.model.profile.Profile;
import io.xeres.app.database.model.profile.ProfileFakes;
import io.xeres.app.service.IdentityService;
import io.xeres.app.service.LocationService;
import io.xeres.app.service.ProfileService;
import io.xeres.app.service.SettingsService;
import io.xeres.app.xrs.service.identity.IdentityRsService;
import io.xeres.app.xrs.service.identity.item.IdentityGroupItem;
import io.xeres.common.rest.config.ImportRsFriendsResponse;
import io.xeres.common.util.ScrambledString;
import jakarta.xml.bind.JAXBException;
import org.bouncycastle.openpgp.PGPException;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.bouncycastle.openpgp.operator.jcajce.JcaPGPDigestCalculatorProviderBuilder;
import org.bouncycastle.openpgp.operator.jcajce.JcePBESecretKeyDecryptorBuilder;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.web.multipart.MultipartFile;

import javax.xml.stream.XMLStreamException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.security.spec.InvalidKeySpecException;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.mockito.Mockito.same;

@ExtendWith(MockitoExtension.class)
class BackupServiceTest
{
	@Mock
	private ProfileService profileService;

	@Mock
	private LocationService locationService;

	@Mock
	private IdentityService identityService;

	@Mock
	private IdentityRsService identityRsService;

	@Mock
	private SettingsService settingsService;

	@InjectMocks
	private BackupService backupService;

	private static ScrambledString passphrase;
	private static PGPSecretKey pgpSecretKey;
	private static KeyPair rsaKeys;
	private static Profile profile;
	private static X509Certificate certificate;
	private static Location location;
	private static IdentityGroupItem identity;

	@BeforeAll
	static void setup() throws PGPException, IOException, CertificateException
	{
		passphrase = new ScrambledString("");
		pgpSecretKey = PGP.generateSecretKey("Foo", "Generated by Xeres Tests", passphrase, 512);
		rsaKeys = RSA.generateKeys(512);

		profile = ProfileFakes.createOwnProfileWithKeys(pgpSecretKey);
		certificate = X509.generateCertificate(pgpSecretKey, passphrase, rsaKeys.getPublic(), "CN=", "CN=-", Instant.EPOCH, Instant.EPOCH, RSSerialVersion.V07_0001.serialNumber());
		location = LocationFakes.createLocationWithCertificate("Home", profile, certificate);
		identity = IdentityFakes.createOwnWithKeys("Foo");
	}

	@Test
	void backupAndRestore() throws JAXBException, PGPException, XMLStreamException, CertificateException, IOException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException
	{
		var friendProfileSecretKey = PGP.generateSecretKey("Bar", "Generated by Xeres Tests", new ScrambledString(""), 512);
		var friendProfile = ProfileFakes.createUnsavedProfileWithKeys(friendProfileSecretKey.getPublicKey());
		friendProfile.setAccepted(true);
		when(profileService.getSecretProfileKey()).thenReturn(pgpSecretKey.getEncoded());
		when(locationService.findOwnLocation()).thenReturn(Optional.of(location));

		when(settingsService.getLocationPrivateKeyData()).thenReturn(rsaKeys.getPrivate().getEncoded());
		when(settingsService.getLocationPublicKeyData()).thenReturn(rsaKeys.getPublic().getEncoded());
		when(settingsService.getLocationCertificate()).thenReturn(certificate.getEncoded());
		when(settingsService.getLocalPort()).thenReturn(6232);

		when(identityService.getOwnIdentity()).thenReturn(identity);

		when(profileService.getAllDiscoverableProfiles()).thenReturn(List.of(profile, friendProfile));

		var result = backupService.backup();
		assertNotNull(result);

		backupService.restore(new MockMultipartFile("backup.xml", result), null, passphrase);

		var secretKeyCaptor = ArgumentCaptor.forClass(PGPSecretKey.class);
		var publicKeyCaptor = ArgumentCaptor.forClass(PGPPublicKey.class);
		verify(profileService).createOwnProfile(anyString(), secretKeyCaptor.capture(), publicKeyCaptor.capture());
		assertEquals(pgpSecretKey.getKeyID(), secretKeyCaptor.getValue().getKeyID());
		assertArrayEquals(pgpSecretKey.getFingerprint(), publicKeyCaptor.getValue().getFingerprint());
		verify(locationService).createOwnLocation(eq("Home"), any(KeyPair.class), any(byte[].class));
		verify(identityRsService).createOwnIdentity(eq("Foo"), any(KeyPair.class), any());
		var friendProfileCaptor = ArgumentCaptor.forClass(Profile.class);
		verify(profileService).createOrUpdateProfile(friendProfileCaptor.capture());
		assertEquals(friendProfile.getPgpIdentifier(), friendProfileCaptor.getValue().getPgpIdentifier());
		assertEquals(friendProfile.getTrust(), friendProfileCaptor.getValue().getTrust());
		assertTrue(friendProfileCaptor.getValue().isAccepted());
	}

	@Test
	void backupAndRestoreWithNewLocation() throws JAXBException, PGPException, XMLStreamException, CertificateException, IOException, NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException
	{
		when(profileService.getSecretProfileKey()).thenReturn(pgpSecretKey.getEncoded());
		when(locationService.findOwnLocation()).thenReturn(Optional.of(location));

		when(settingsService.getLocationPrivateKeyData()).thenReturn(rsaKeys.getPrivate().getEncoded());
		when(settingsService.getLocationPublicKeyData()).thenReturn(rsaKeys.getPublic().getEncoded());
		when(settingsService.getLocationCertificate()).thenReturn(certificate.getEncoded());
		when(settingsService.getLocalPort()).thenReturn(6232);

		when(identityService.getOwnIdentity()).thenReturn(identity);

		when(profileService.getAllDiscoverableProfiles()).thenReturn(List.of(profile));

		var result = backupService.backup();
		assertNotNull(result);

		backupService.restore(new MockMultipartFile("backup.xml", result), "newLocation", passphrase);

		verify(profileService).createOwnProfile(anyString(), any(PGPSecretKey.class), any(PGPPublicKey.class));
		verify(locationService).generateOwnLocation(eq("newLocation"), any(ScrambledString.class));
		verify(identityRsService).generateOwnIdentity(anyString(), eq(true), any(ScrambledString.class));
	}

	@Test
	void importProfileFromRs_WithNullFile_ThrowsException()
	{
		assertThatThrownBy(() -> backupService.importProfileFromRs(null, "Home", passphrase))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importProfileFromRs_WithTooBigFile_ThrowsException()
	{
		var file = new MockMultipartFile("keyring.bin", new byte[1024 * 1024]);

		assertThatThrownBy(() -> backupService.importProfileFromRs(file, "Home", passphrase))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importProfileFromRs_WithEmptyLocationName_ThrowsException()
	{
		var file = new MockMultipartFile("keyring.bin", new byte[1]);

		assertThatThrownBy(() -> backupService.importProfileFromRs(file, "", passphrase))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importProfileFromRs_WithNullPassphrase_ThrowsException()
	{
		var file = new MockMultipartFile("keyring.bin", new byte[1]);

		assertThatThrownBy(() -> backupService.importProfileFromRs(file, "Home", null))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importProfileFromRs_WithWrongPassphrase_ThrowsException() throws PGPException, IOException, InvalidKeyException
	{
		var oldPassphrase = new ScrambledString("oldPassphrase");
		var rsSecretKey = PGP.generateSecretKey("Foo", "(Generated by RetroShare) <>", oldPassphrase, 512);
		var file = new MockMultipartFile("keyring.bin", rsSecretKey.getEncoded());

		assertThatThrownBy(() -> backupService.importProfileFromRs(file, "Home", passphrase))
				.isInstanceOf(IllegalArgumentException.class);

		verify(profileService, never()).createOwnProfile(anyString(), any(PGPSecretKey.class), any(PGPPublicKey.class));
		verify(locationService, never()).generateOwnLocation(anyString(), any(ScrambledString.class));
		verify(identityRsService, never()).generateOwnIdentity(anyString(), anyBoolean(), any(ScrambledString.class));
	}

	@Test
	void importProfileFromRs_Success() throws PGPException, IOException, InvalidKeyException
	{
		var newPassphrase = new ScrambledString("newPassphrase");
		var rsSecretKey = PGP.generateSecretKey("Foo", "(Generated by RetroShare) <>", newPassphrase, 512);
		var file = new MockMultipartFile("keyring.bin", rsSecretKey.getEncoded());

		backupService.importProfileFromRs(file, "Home", newPassphrase);

		var captor = ArgumentCaptor.forClass(PGPSecretKey.class);
		verify(profileService).createOwnProfile(eq("Foo"), captor.capture(), any(PGPPublicKey.class));
		verify(locationService).generateOwnLocation(eq("Home"), eq(newPassphrase));
		verify(identityRsService).generateOwnIdentity(eq("Foo"), eq(true), eq(newPassphrase));

		assertDoesNotThrow(() ->
		{
			try
			{
				captor.getValue().extractPrivateKey(new JcePBESecretKeyDecryptorBuilder(new JcaPGPDigestCalculatorProviderBuilder().build())
						.build(newPassphrase.getAsCharArrayToClear()));
			}
			catch (PGPException e)
			{
				throw new RuntimeException(e);
			}
		});
	}

	@Test
	void importProfileFromRs_FromAscFile_Success() throws PGPException, IOException, InvalidKeyException
	{
		var newPassphrase = new ScrambledString("newPassphrase");
		var rsSecretKey = PGP.generateSecretKey("Foo", "(Generated by RetroShare) <>", newPassphrase, 512);

		// The public key block is skipped, followed by empty lines, then the private key block
		var content = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n"
				+ "dummy\n"
				+ "-----END PGP PUBLIC KEY BLOCK-----\n"
				+ "\n"
				+ "\n"
				+ createArmoredSecretKey(rsSecretKey);

		var file = new MockMultipartFile("keyring.asc", "keyring.asc", null, content.getBytes(StandardCharsets.US_ASCII));

		backupService.importProfileFromRs(file, "Home", newPassphrase);

		verify(profileService).createOwnProfile(eq("Foo"), any(PGPSecretKey.class), any(PGPPublicKey.class));
		verify(locationService).generateOwnLocation(eq("Home"), eq(newPassphrase));
		verify(identityRsService).generateOwnIdentity(eq("Foo"), eq(true), eq(newPassphrase));
	}

	@Test
	void importFriendsFromRs_WithNullFile_ThrowsException()
	{
		assertThatThrownBy(() -> backupService.importFriendsFromRs(null))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importFriendsFromRs_WithTooLargeFile_ThrowsException()
	{
		var file = new MockMultipartFile("friends.xml", new byte[1024 * 1024 * 10]);

		assertThatThrownBy(() -> backupService.importFriendsFromRs(file))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void importFriendsFromRs_Success() throws JAXBException, IOException, XMLStreamException, PGPException
	{
		var profile1 = createProfileWithKeys("Alice");
		var profile2 = createProfileWithKeys("Bob");

		when(profileService.getProfileFromRSId(any(RSId.class))).thenReturn(profile1, profile2);

		var response = backupService.importFriendsFromRs(createFriendsXmlFile(
				RSIdFakes.createRsCertificate(profile1).getArmored(),
				RSIdFakes.createRsCertificate(profile2).getArmored()));

		assertEquals(new ImportRsFriendsResponse(2, 0), response);
		verify(profileService).createOrUpdateProfile(same(profile1));
		verify(profileService).createOrUpdateProfile(same(profile2));
		assertTrue(profile1.isAccepted());
		assertTrue(profile2.isAccepted());
	}

	@Test
	void importFriendsFromRs_WithError_ReturnsErrorCount() throws JAXBException, IOException, XMLStreamException, PGPException
	{
		when(profileService.getProfileFromRSId(any(RSId.class))).thenThrow(new RuntimeException("test"));

		var response = backupService.importFriendsFromRs(createFriendsXmlFile(
				RSIdFakes.createRsCertificate(createProfileWithKeys("Alice")).getArmored()));

		assertEquals(new ImportRsFriendsResponse(0, 1), response);
		verify(profileService, never()).createOrUpdateProfile(any());
	}

	private static Profile createProfileWithKeys(String name) throws PGPException, IOException
	{
		return ProfileFakes.createOwnProfileWithKeys(PGP.generateSecretKey(name, null, passphrase, 512));
	}

	private static String createArmoredSecretKey(PGPSecretKey secretKey) throws IOException
	{
		var encoded = Base64.getEncoder().encodeToString(secretKey.getEncoded());
		var sb = new StringBuilder("-----BEGIN PGP PRIVATE KEY BLOCK-----\n\n\n");
		for (var i = 0; i < encoded.length(); i += 64)
		{
			sb.append(encoded, i, Math.min(i + 64, encoded.length())).append('\n');
		}
		sb.append("-----END PGP PRIVATE KEY BLOCK-----\n");
		return sb.toString();
	}

	private static MultipartFile createFriendsXmlFile(String... certificates)
	{
		var sb = new StringBuilder();
		sb.append("<root><pgpIDs>");
		for (var certificate : certificates)
		{
			sb.append("<pgpID><sslID certificate=\"")
					.append(certificate.replace("\r", " ").replace("\n", " "))
					.append("\"/></pgpID>");
		}
		sb.append("</pgpIDs></root>");
		return new MockMultipartFile("friends.xml", sb.toString().getBytes(StandardCharsets.UTF_8));
	}
}