/*
 * Copyright (c) 2025 by David Gerber - https://zapek.com
 *
 * This file is part of Xeres.
 *
 * Xeres is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Xeres is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Xeres.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.xeres.ui.custom;

import io.xeres.common.i18n.I18nUtils;
import io.xeres.ui.custom.asyncimage.AsyncImageView;
import io.xeres.ui.custom.asyncimage.ImageCache;
import javafx.beans.NamedArg;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.layout.StackPane;

import java.io.IOException;
import java.util.ResourceBundle;
import java.util.function.Function;

/**
 * An image placeholder that allows to select/remove the image.
 */
public class ImageSelectorView extends StackPane
{
	private static final double BUTTON_OPACITY = 0.8;

	@FXML
	private AsyncImageView imageView;

	@FXML
	private Button selectButton;

	@FXML
	private Button deleteButton;

	private boolean deletable;

	private final Double fitWidth;
	private final Double fitHeight;

	public ImageSelectorView(@NamedArg(value = "fitWidth", defaultValue = "64.0") Double fitWidth, @NamedArg(value = "fitHeight", defaultValue = "64.0") Double fitHeight)
	{
		super();
		ResourceBundle bundle = I18nUtils.getBundle();

		setAlignment(Pos.TOP_LEFT);
		var loader = new FXMLLoader(ImageSelectorView.class.getResource("/view/custom/image_selector_view.fxml"), bundle);
		loader.setRoot(this);
		loader.setController(this);

		try
		{
			loader.load();
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}

		this.fitWidth = fitWidth;
		this.fitHeight = fitHeight;
	}

	public void setImageLoader(Function<String, byte[]> loader)
	{
		imageView.setLoader(loader);
	}

	public void setImageCache(ImageCache imageCache)
	{
		imageView.setImageCache(imageCache);
	}

	public void setImageUrl(String url)
	{
		imageView.setUrl(url);
	}

	public void setImage(Image image)
	{
		imageView.setImageProper(image);
	}

	public void setOnSelectAction(EventHandler<ActionEvent> value)
	{
		selectButton.setOnAction(value);
	}

	public void setOnDeleteAction(EventHandler<ActionEvent> value)
	{
		deleteButton.setOnAction(value);
	}

	/**
	 * Shows the edit buttons.
	 *
	 * @param editable true if the image can be added and removed
	 */
	public void setEditable(boolean editable)
	{
		setEditable(editable, editable);
	}

	/**
	 * Shows the edit buttons.
	 * <p>This version is needed in case an image is not a real image (for example autogenerated)
	 * and hence the delete button would make no sense and has to be set to false.
	 *
	 * @param editable  true if an image can be added
	 * @param deletable true if the image can also be removed
	 */
	public void setEditable(boolean editable, boolean deletable)
	{
		this.deletable = deletable;

		selectButton.setVisible(editable);

		if (deletable)
		{
			if (imageView.getImage() != null && !imageView.getImage().isError())
			{
				deleteButton.setVisible(true);
			}
			else
			{
				deleteButton.setVisible(false);
			}
		}
		else
		{
			deleteButton.setVisible(false);
		}
	}

	private void setImageOpacity(double opacity)
	{
		selectButton.setOpacity(opacity);
		if (imageView.getImage() != null)
		{
			deleteButton.setOpacity(opacity);
		}
	}

	@FXML
	private void initialize()
	{
		if (fitWidth != null && fitWidth != 0)
		{
			imageView.setFitWidth(fitWidth);
		}
		if (fitHeight != null && fitHeight != 0)
		{
			imageView.setFitHeight(fitHeight);
		}

		imageView.setOnMouseEntered(_ -> setImageOpacity(BUTTON_OPACITY));
		imageView.setOnMouseExited(_ -> setImageOpacity(0.0));
		selectButton.setOnMouseEntered(_ -> setImageOpacity(BUTTON_OPACITY));
		selectButton.setOnMouseExited(_ -> setImageOpacity(0.0));
		deleteButton.setOnMouseEntered(_ -> setImageOpacity(BUTTON_OPACITY));
		deleteButton.setOnMouseExited(_ -> setImageOpacity(0.0));

		imageView.imageProperty().addListener((_, _, newValue) -> {
			if (newValue != null && !newValue.isError())
			{
				if (deletable)
				{
					deleteButton.setVisible(true);
				}
			}
			else
			{
				if (deletable)
				{
					deleteButton.setVisible(false);
				}
			}
		});
	}
}
