package io.xeres.app.xrs.item;

public enum ItemPriority
{
	/**
	 * Anything that happens in the background and is not really urgent (for example discovery exchanges, file transfers, ...)
	 */
	BACKGROUND(2),

	/**
	 * The default priority.
	 */
	DEFAULT(3),

	/**
	 * High priority. Has consequences for other services and should be serviced quickly (for example GxS exchanges).
	 */
	HIGH(6),

	/**
	 * Generated by a  user and requires immediate feedback (for example chat, typing feedback, ...)
	 */
	INTERACTIVE(7),

	/**
	 * Must be acknowledged by the other peer quickly, or it will have disruptive effects (for example, heartbeats).
	 */
	IMPORTANT(8),

	/**
	 * Must be carried away immediately or it won't be usable (for example RTT measurements).
	 */
	REALTIME(9);

	private final int priority;

	ItemPriority(int priority)
	{
		this.priority = priority;
	}

	public int getPriority()
	{
		return priority;
	}
}

